sensor_msgs/Image             imagein            #输入图像
---
bool                          result             #是否检测成功
sensor_msgs/Image             imageout           #输出结果图像
IfAlgorhmittargetpoint2f[]    targetpointout     #目标点 
IfAlgorhmitpoint2f[]          lasertrackout      #激光轨迹